In [ ]:
#esercizio_1 
#Abbiamo una lista di liste: mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] 
#Che tipo di struttura dati o matematica potrebbe rappresentare? 
#Notare che tutte le liste "interne" sono della stessa dimensione 
#Come facciamo per accedere ad un elemento in particolare?

In [42]:
import numpy as npy #importo numpy

In [5]:
mat =[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]] # creo la lista

In [9]:
mat_npy=npy.array(mat) #casting

In [11]:
mat_npy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
mat_npy[#n°lista , n° all'interno della lista selezionata]

7

In [ ]:
#esercizio_2
#Importiamo il modulo math e proviamo a usare le funzioni 
# .sin() .cos() .factorial() e la variabile .pi 
#la riconoscete?

In [2]:
import math #importo il modulo math

In [14]:
math.sin(0) #funzione seno

0.0

In [16]:
math.cos(0) #funzione coseno

1.0

In [18]:
math.factorial(10) #funzione fattoriale

3628800

In [28]:
math.pi*2 #è la variante pi-greco

6.283185307179586

In [ ]:
#esercizio_3
#Proviamo a eseguire math.degrees(math.pi) 
#Qual è e cosa significa il risultato? 
#Per saperne di più su questa funzione possiamo usare help(math.degrees)

In [30]:
math.degrees(math.pi)

180.0

In [32]:
help(math.degrees) 
#math.degrees converte 
#il pi-greco in misura dell'angolo in gradi radiali

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



In [ ]:
#esercizio_4
#L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno: 
#lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350] 
#trasformiamola in un array NumPy (casting): lst = np.array(lst) 
#e rispondiamo alle domande del CEO della Object SpA: 
#qual è stata la vendita massima mensile? E quella minima? 
#quali sono le vendite mensili maggiori di 5000 oggetti? E quante ne sono? 
#quali sono le vendite minori di 3000 oggetti? 
#in media quanti oggetti sono stati venduti al mese?

In [36]:
lst=[2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

In [73]:
lst_npy=npy.array(lst) #casting

In [93]:
lst_npy.min()#valore minimo

1280

In [95]:
lst_npy.max()#valore massimo

8150

In [99]:
lst_npy>5000#valori maggiori di 5000

array([False,  True,  True, False, False, False, False, False,  True,
        True,  True,  True])

In [121]:
lst_over5000=lst_npy [lst_npy>5000]

In [123]:
lst_over5000

array([5500, 7200, 6410, 8150, 7100, 5350])

In [135]:
lst_under3000=lst_npy[lst_npy<3000]#minore di 3000

In [133]:
lst_under3000

array([2000, 1280, 1900, 2500])

In [141]:
lst_npy.mean()#media vendite mensili

4634.166666666667